SELECT
    EXTRACT(MONTH FROM START_DATE) AS MONTH,
    B.CAR_ID,
    COUNT(*) AS RECORDS
FROM
    (SELECT
        CAR_ID,
        COUNT(*) AS RECORDS
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        RECORDS >= 5
    ) A
    INNER JOIN
        CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        ON A.CAR_ID = B.CAR_ID
WHERE
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    MONTH,
    B.CAR_ID
HAVING
    RECORDS > 0
ORDER BY
    MONTH ,
    B.CAR_ID DESC
;