SELECT
    B.DEPT_ID ,
    DEPT_NAME_EN ,
    ROUND(AVG(SAL)) AS AVG_SAL
FROM
    HR_EMPLOYEES A
    INNER JOIN
        HR_DEPARTMENT B
        ON A.DEPT_ID = B.DEPT_ID
GROUP BY
    B.DEPT_ID ,
    DEPT_NAME_EN
ORDER BY
    AVG_SAL DESC
;