SELECT
    A.ITEM_ID,
    ITEM_NAME,
    RARITY
FROM
    ITEM_INFO A
    LEFT JOIN
        ITEM_TREE B
        ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE
    PARENT_ITEM_ID IS NULL
ORDER BY
    A.ITEM_ID DESC
;

-- 다른사람 풀이
-- EXISTS를 이용한 풀이
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO INFO
WHERE NOT EXISTS (SELECT 1  FROM ITEM_TREE TREE WHERE TREE.PARENT_ITEM_ID = INFO.ITEM_ID)
ORDER BY ITEM_ID DESC
;
