SELECT
    CAR_ID,
    CASE
        WHEN COUNT(CAR_ID) = 2 THEN '대여중'
        ELSE AVAILABILITY
        END AS AVAILABILITY
FROM (
    SELECT DISTINCT
        CAR_ID ,
        CASE
            WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
            ELSE '대여 가능'
        END AS AVAILABILITY
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
) A
GROUP BY
    CAR_ID
ORDER BY
    CAR_ID DESC
;

-- 다른 사람 풀이
-- 1, 0(True, False)의 sum 으로 풀이하면 됐네
SELECT CAR_ID,
    CASE
        WHEN SUM(
            CASE WHEN START_DATE <= '2022-10-16' 
            AND END_DATE >= '2022-10-16' 
            THEN 1 ELSE 0 END) = 0 
        THEN '대여 가능' ELSE '대여중' 
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;