WITH TB AS (
    SELECT
        REST_ID ,
        FOOD_TYPE ,
        FAVORITES ,
        ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS SEQ
    FROM
        REST_INFO
)
SELECT
   A. FOOD_TYPE,
    A.REST_ID,
    REST_NAME,
    A.FAVORITES
FROM
    REST_INFO A
    INNER JOIN
        TB B
        ON A.REST_ID = B.REST_ID
        AND SEQ = 1
ORDER BY
    FOOD_TYPE DESC
;

-- GROUP BY를 이용하는 방법
SELECT
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM
    REST_INFO
WHERE
    (FOOD_TYPE, FAVORITES) IN 
        (SELECT FOOD_TYPE, MAX(FAVORITES)
        FROM REST_INFO
        GROUP BY FOOD_TYPE )
ORDER BY 
    FOOD_TYPE DESC
;