SELECT
    COUNT(*) AS FISH_COUNT,
    FISH_NAME
FROM
    FISH_INFO A
    INNER JOIN
        FISH_NAME_INFO B
        ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY
    B.FISH_TYPE,
    FISH_NAME
ORDER BY
    COUNT(*) DESC
;