SELECT
    A.ID,
    A.GENOTYPE,
    B.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA A
    INNER JOIN
        ECOLI_DATA B -- 부모 데이터 조회용
        ON A.PARENT_ID = B.ID
        AND A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
ORDER BY
    A.ID
;