SELECT
    A.PRODUCT_CODE,
    SUM(B.SALES_AMOUNT * A.PRICE) AS ALL_PRICE
FROM
    PRODUCT A
    INNER JOIN
        OFFLINE_SALE B
        ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY
    A.PRODUCT_CODE
ORDER BY
    ALL_PRICE DESC,
    PRODUCT_CODE
;