-- 당일에 반납해도 1일 사용한 것이기 때문에 average_duration을 구할 때 +1해줘야 함
SELECT * 
FROM
    (SELECT
        CAR_ID,
        ROUND(AVG(DATEDIFF(END_DATE, START_DATE)) + 1, 1) AS AVERAGE_DURATION
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY
        CAR_ID
    ) A
WHERE
    AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC,
    CAR_ID DESC
;