WITH USR AS (
    SELECT
        USER_ID ,
        GENDER ,
        AGE ,
        EXTRACT(YEAR FROM JOINED) AS JOINED_YEAR ,
        EXTRACT(MONTH FROM JOINED) AS JOINED_MONTH ,
        COUNT(USER_ID) OVER() AS TOTAL
    FROM
        USER_INFO
    WHERE
        EXTRACT(YEAR FROM JOINED) = 2021
)
SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR ,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH ,
    COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS ,
    ROUND(COUNT(DISTINCT A.USER_ID) / TOTAL, 1) AS PUCHASED_RATIO
FROM
    ONLINE_SALE A
    INNER JOIN
        USR B
        ON A.USER_ID = B.USER_ID
GROUP BY
    YEAR ,
    MONTH
ORDER BY
    YEAR ,
    MONTH
;