SELECT
    B.PRODUCT_ID ,
    A.PRODUCT_NAME ,
    PRICE * SUM(AMOUNT) AS TOTAL
FROM
    FOOD_PRODUCT A
    INNER JOIN
        FOOD_ORDER B
        ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE
    PRODUCE_DATE BETWEEN DATE_FORMAT('2022-05-01', '%Y-%m-%d') AND DATE_FORMAT('2022-05-31', '%Y-%m-%d')
GROUP BY
    B.PRODUCT_ID ,
    A.PRODUCT_NAME
ORDER BY
    TOTAL DESC,
    B.PRODUCT_ID
;