SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    GENDER ,
    COUNT(DISTINCT A.USER_ID)
FROM
    ONLINE_SALE A
    INNER JOIN
        USER_INFO B
        ON A.USER_ID = B.USER_ID
        AND B.GENDER IS NOT NULL
GROUP BY
    YEAR,
    MONTH,
    GENDER
ORDER BY
    YEAR,
    MONTH,
    GENDER
;