SELECT
    A.REST_ID ,
    A.REST_NAME ,
    A.FOOD_TYPE ,
    A.FAVORITES ,
    A.ADDRESS ,
    ROUND(AVG(REVIEW_SCORE), 2) AS AVG_SCORE
FROM
    REST_INFO A
    INNER JOIN
        REST_REVIEW B
        ON A.REST_ID = B.REST_ID
WHERE
    ADDRESS LIKE '서울%'
GROUP BY
    A.REST_ID ,
    REST_NAME ,
    FOOD_TYPE ,
    FAVORITES ,
    ADDRESS
ORDER BY
    AVG_SCORE DESC ,
    FAVORITES DESC