SELECT
    A.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(TOTAL) AS TOTAL_PRICE
FROM
    (SELECT
        A.BOOK_ID ,
        AUTHOR_ID ,
        CATEGORY ,
        SUM(SALES * PRICE) AS TOTAL
    FROM
        BOOK_SALES S
        INNER JOIN
            BOOK A
            ON S.BOOK_ID = A.BOOK_ID
            AND S.SALES_DATE LIKE '2022-01%'
    GROUP BY
        A.BOOK_ID ,
        AUTHOR_ID ,
        CATEGORY
) A
INNER JOIN
    AUTHOR B
    ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY
    A.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY
ORDER BY
    A.AUTHOR_ID,
    CATEGORY DESC
;

-- 다른 사람 풀이
-- 될 것 같긴 했는데 역시 되는군
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM AUTHOR A, BOOK B, BOOK_SALES S
WHERE A.AUTHOR_ID = B.AUTHOR_ID AND B.BOOK_ID = S.BOOK_ID 
    AND S.SALES_DATE LIKE '2022-01-%'
GROUP BY A.AUTHOR_ID, B.CATEGORY 
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC