WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS(
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID
    FROM ECOLI_DATA JOIN FIRST_GEN ON ECOLI_DATA.PARENT_ID = FIRST_GEN.ID
)
SELECT ECOLI_DATA.ID
FROM ECOLI_DATA JOIN SECOND_GEN ON ECOLI_DATA.PARENT_ID = SECOND_GEN.ID

-- 다른 사람 풀이
-- RECURSIVE CTE라는 방법이 있다
WITH RECURSIVE GEN_DATA AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GEN
    FROM
        ECOLI_DATA
    WHERE
        PARENT_ID IS NULL
    UNION ALL
    SELECT
        E.ID,
        E.PARENT_ID,
        (GEN + 1) AS GEN
    FROM 
        ECOLI_DATA E
    INNER JOIN
        GEN_DATA G
        ON E.PARENT_ID = G.ID
)
SELECT ID, GEN FROM GEN_DATA;

